In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
%matplotlib inline

### Regression

##### Importing data

In [3]:
movreg_data= pd.read_csv('Movie_regression.csv')

In [4]:
movreg_data.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  
0          223.840  Thriller              23            494       48000  
1          243.456     Drama              42            462       43200  
2         2022.400    Comedy              38            458       69400  
3          225.344     Drama              45            472       66800  
4          225.792     Drama              55            395       72400

In [5]:
movreg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
Marketing expense      506 non-null float64
Production expense     506 non-null float64
Multiplex coverage     506 non-null float64
Budget                 506 non-null float64
Movie_length           506 non-null float64
Lead_ Actor_Rating     506 non-null float64
Lead_Actress_rating    506 non-null float64
Director_rating        506 non-null float64
Producer_rating        506 non-null float64
Critic_rating          506 non-null float64
Trailer_views          506 non-null int64
3D_available           506 non-null object
Time_taken             494 non-null float64
Twitter_hastags        506 non-null float64
Genre                  506 non-null object
Avg_age_actors         506 non-null int64
Num_multiplex          506 non-null int64
Collection             506 non-null int64
dtypes: float64(12), int64(4), object(2)
memory usage: 71.2+ KB


##### Missing Values

In [6]:
movreg_data['Time_taken'].mean()

157.39149797570855

In [7]:
movreg_data['Time_taken'].fillna(value= movreg_data['Time_taken'].mean(), inplace= True)

In [8]:
movreg_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 18 columns):
Marketing expense      506 non-null float64
Production expense     506 non-null float64
Multiplex coverage     506 non-null float64
Budget                 506 non-null float64
Movie_length           506 non-null float64
Lead_ Actor_Rating     506 non-null float64
Lead_Actress_rating    506 non-null float64
Director_rating        506 non-null float64
Producer_rating        506 non-null float64
Critic_rating          506 non-null float64
Trailer_views          506 non-null int64
3D_available           506 non-null object
Time_taken             506 non-null float64
Twitter_hastags        506 non-null float64
Genre                  506 non-null object
Avg_age_actors         506 non-null int64
Num_multiplex          506 non-null int64
Collection             506 non-null int64
dtypes: float64(12), int64(4), object(2)
memory usage: 71.2+ KB


##### Dummy Variables

In [9]:
movreg_data['3D_available'].unique()

array(['YES', 'NO'], dtype=object)

In [10]:
movreg_data['Genre'].unique()

array(['Thriller', 'Drama', 'Comedy', 'Action'], dtype=object)

In [11]:
movreg_data= pd.get_dummies(data= movreg_data, columns=['3D_available', 'Genre'], drop_first=True)

In [12]:
movreg_data.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   
2            7.515           7.44         547051      147.88         2022.400   
3            7.020           8.26         516279      185.36          225.344   
4            7.070           8.26         531448      176.48          225.792   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy  \
0              23            494       48000                 1             0   
1              42            462       43200                 0             0   
2              38            458       69400                 0             1   
3              45            472       66800                 1             0   
4              55            395       72400                 0             0   

   Genre_Drama  Genre_Thriller  
0            0               1  
1            1               0  
2            0               0  
3            1               0  
4            1               0

##### Splitting the data

In [13]:
X= movreg_data.drop(['Collection'], axis=1)
X.head(2)

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095             7.91   
1         152.4               7.505                7.650             7.44   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   

   Avg_age_actors  Num_multiplex  3D_available_YES  Genre_Comedy  Genre_Drama  \
0              23            494                 1             0            0   
1              42            462                 0             0            1   

   Genre_Thriller  
0               1  
1               0

In [14]:
y= movreg_data['Collection']

In [15]:
y.head(2)

0    48000
1    43200
Name: Collection, dtype: int64

##### Train-Test Split and Normalization

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=101)

In [18]:
from sklearn.preprocessing import StandardScaler

In [19]:
sc = StandardScaler()

In [20]:
X_train_std= sc.fit_transform(X_train)

In [21]:
X_test_std= sc.fit_transform(X_test)

In [22]:
X_train_std[:2]

array([[-0.41461886, -0.85460156,  1.29472643,  0.06030019, -0.79942184,
        -1.73626868, -1.61917004, -1.6539163 , -1.6785072 , -0.2271171 ,
         0.73709226, -1.24798269, -0.20743028, -1.39771909, -1.83759824,
        -1.09893142, -0.66160594, -0.48525664,  1.3222327 ],
       [-0.40889626, -0.05439889,  1.22416496, -0.3112873 , -2.13850253,
        -0.69663257, -0.62113515, -0.77042486, -0.70636557, -1.0363566 ,
         0.76049129, -1.24167013, -0.73498584, -1.55850454, -1.72345322,
        -1.09893142, -0.66160594, -0.48525664,  1.3222327 ]])

In [23]:
X_test_std[:2]

array([[-0.43505676, -1.53810975,  1.16190457,  1.92354444, -1.38217084,
        -0.90664168, -0.93586611, -0.88147437, -0.92901292,  1.90781483,
         1.23432587,  0.10720387,  0.11784511, -0.97320356, -1.15145183,
         0.87098834, -0.6761234 , -0.4938648 ,  1.3540064 ],
       [-0.42983715, -1.28598087,  0.87182342,  1.02007048, -0.57877539,
        -1.06751999, -1.08676309, -1.15831721, -1.09516827,  0.70917913,
         1.04330005,  0.56573359, -0.23194862,  1.30788687, -1.47038138,
        -1.14812099, -0.6761234 ,  2.02484567, -0.73854895]])

#### SVR

In [24]:
from sklearn.svm import SVR

In [25]:
svr= SVR(kernel='linear', C=1000)

In [26]:
svr_model= svr.fit(X_train_std, y_train)

In [27]:
svr_predict= svr.predict(X_test_std)

In [28]:
svr_predict[:10]

array([72934.56030729, 58949.42705629, 35902.96377051, 38664.15046627,
       58287.16224528, 60218.32197487, 74916.90274198, 31176.12025186,
       55833.87314755, 18114.65755782])

##### Model Evaluation

In [29]:
from sklearn.metrics import mean_squared_error, r2_score

In [30]:
print('Mean Squared Error: ', mean_squared_error(y_test, svr_predict))

Mean Squared Error:  174120798.604478


In [31]:
print('r2_score: ', r2_score(y_test, svr_predict))

r2_score:  0.6081246510959541


### Classification

##### Importing data

In [32]:
movclas_data= pd.read_csv('Movie_classification.csv')
movclas_data.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating  Trailer_views 3D_available  Time_taken  \
0            7.995           7.94         527367          YES      109.60   
1            7.470           7.44         494055           NO      146.64   
2            7.515           7.44         547051           NO      147.88   
3            7.020           8.26         516279          YES      185.36   
4            7.070           8.26         531448           NO      176.48   

   Twitter_hastags     Genre  Avg_age_actors  Num_multiplex  Collection  \
0          223.840  Thriller              23            494       48000   
1          243.456     Drama              42            462       43200   
2         2022.400    Comedy              38            458       69400   
3          225.344     Drama              45            472       66800   
4          225.792     Drama              55            395       72400   

   Start_Tech_Oscar  
0                 1  
1                 0  
2                 1  
3                 1  
4                 1

In [33]:
movclas_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
Marketing expense      506 non-null float64
Production expense     506 non-null float64
Multiplex coverage     506 non-null float64
Budget                 506 non-null float64
Movie_length           506 non-null float64
Lead_ Actor_Rating     506 non-null float64
Lead_Actress_rating    506 non-null float64
Director_rating        506 non-null float64
Producer_rating        506 non-null float64
Critic_rating          506 non-null float64
Trailer_views          506 non-null int64
3D_available           506 non-null object
Time_taken             494 non-null float64
Twitter_hastags        506 non-null float64
Genre                  506 non-null object
Avg_age_actors         506 non-null int64
Num_multiplex          506 non-null int64
Collection             506 non-null int64
Start_Tech_Oscar       506 non-null int64
dtypes: float64(12), int64(5), object(2)
memory usage: 75.2+ KB


##### Missing Values

In [34]:
movclas_data['Time_taken'].mean()

157.39149797570855

In [35]:
movclas_data['Time_taken'].fillna(value= movreg_data['Time_taken'].mean(), inplace= True)

In [36]:
movclas_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 19 columns):
Marketing expense      506 non-null float64
Production expense     506 non-null float64
Multiplex coverage     506 non-null float64
Budget                 506 non-null float64
Movie_length           506 non-null float64
Lead_ Actor_Rating     506 non-null float64
Lead_Actress_rating    506 non-null float64
Director_rating        506 non-null float64
Producer_rating        506 non-null float64
Critic_rating          506 non-null float64
Trailer_views          506 non-null int64
3D_available           506 non-null object
Time_taken             506 non-null float64
Twitter_hastags        506 non-null float64
Genre                  506 non-null object
Avg_age_actors         506 non-null int64
Num_multiplex          506 non-null int64
Collection             506 non-null int64
Start_Tech_Oscar       506 non-null int64
dtypes: float64(12), int64(5), object(2)
memory usage: 75.2+ KB


##### Dummy Variables

In [37]:
movclas_data= pd.get_dummies(data= movclas_data, columns=['3D_available', 'Genre'], drop_first=True)

In [38]:
movclas_data.head()

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   
2            20.5458               69.14               0.531  39912.675   
3            20.6474               59.36               0.542  38873.890   
4            21.3810               59.36               0.542  39701.585   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095            7.910   
1         152.4               7.505                7.650            7.440   
2         134.6               7.485                7.570            7.495   
3         119.3               6.895                7.035            6.920   
4         127.7               6.920                7.070            6.815   

   Producer_rating  Critic_rating       ...        Time_taken  \
0            7.995           7.94       ...            109.60   
1            7.470           7.44       ...            146.64   
2            7.515           7.44       ...            147.88   
3            7.020           8.26       ...            185.36   
4            7.070           8.26       ...            176.48   

   Twitter_hastags  Avg_age_actors  Num_multiplex  Collection  \
0          223.840              23            494       48000   
1          243.456              42            462       43200   
2         2022.400              38            458       69400   
3          225.344              45            472       66800   
4          225.792              55            395       72400   

   Start_Tech_Oscar  3D_available_YES  Genre_Comedy  Genre_Drama  \
0                 1                 1             0            0   
1                 0                 0             0            1   
2                 1                 0             1            0   
3                 1                 1             0            1   
4                 1                 0             0            1   

   Genre_Thriller  
0               1  
1               0  
2               0  
3               0  
4               0  

[5 rows x 21 columns]

##### Splitting and Normalizing data

In [39]:
X= movclas_data.drop(['Start_Tech_Oscar'], axis=1)
X.head(2)

Marketing expense  Production expense  Multiplex coverage     Budget  \
0            20.1264               59.62               0.462  36524.125   
1            20.5462               69.14               0.531  35668.655   

   Movie_length  Lead_ Actor_Rating  Lead_Actress_rating  Director_rating  \
0         138.7               7.825                8.095             7.91   
1         152.4               7.505                7.650             7.44   

   Producer_rating  Critic_rating  Trailer_views  Time_taken  Twitter_hastags  \
0            7.995           7.94         527367      109.60          223.840   
1            7.470           7.44         494055      146.64          243.456   

   Avg_age_actors  Num_multiplex  Collection  3D_available_YES  Genre_Comedy  \
0              23            494       48000                 1             0   
1              42            462       43200                 0             0   

   Genre_Drama  Genre_Thriller  
0            0               1  
1            1               0

In [40]:
y= movclas_data['Start_Tech_Oscar']
y.head()

0    1
1    0
2    1
3    1
4    1
Name: Start_Tech_Oscar, dtype: int64

In [41]:
X_std= sc.fit_transform(X)

In [42]:
X_std[:2]

array([[-0.41978194, -1.2879095 ,  0.14421743,  0.41367189, -0.12001342,
        -0.17945092, -0.08603165, -0.10356891, -0.18645869,  0.19593514,
         1.12573279, -1.54712448, -0.35339768, -1.29440816, -0.48050976,
         0.16037616,  0.90200891, -0.66452648, -0.48699468,  1.32854331],
       [-0.41733926, -0.59338101,  0.74026221,  0.19427445,  0.36716642,
        -0.48327998, -0.50853429, -0.54744633, -0.68714352, -0.56273629,
         0.64189576, -0.34805157, -0.16599956,  0.22543063, -0.78174928,
        -0.10125846, -1.1086365 , -0.66452648,  2.05341054, -0.7527041 ]])

In [43]:
X_train, X_test, y_train, y_test= train_test_split(X_std, y, test_size=0.2, random_state=101)

In [44]:
X_train.shape

(404, 20)

In [45]:
X_test.shape

(102, 20)

#### SVM Classifier

In [46]:
from sklearn import svm

In [47]:
svm_= svm.SVC(kernel='linear', C=0.01)

In [48]:
svm_model= svm_.fit(X_train, y_train)

In [51]:
svm_predict=svm_.predict(X_test)

In [53]:
svm_predict[:10]

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

##### Model Evaluation

In [54]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [55]:
print('Accuracy Score: ', accuracy_score(y_test, svm_predict))

Accuracy Score:  0.6666666666666666


In [56]:
print('Confusion Matrix', end='\n')
confusion_matrix(y_test, svm_predict)

Confusion Matrix


array([[ 7, 33],
       [ 1, 61]], dtype=int64)

Number of Support Vectors

In [57]:
svm_.n_support_

array([190, 195])

##### Grid Search

In [58]:
from sklearn.model_selection import GridSearchCV

In [59]:
params= {'C':(0.001,0.005,0.01,0.05,0.1,0.5,1,5,10,100,500,1000)}

In [61]:
svm_1= svm.SVC(kernel='linear')

In [62]:
svm_grid= GridSearchCV(estimator=svm_1, param_grid=params, n_jobs=-1, cv=10, verbose=1, scoring='accuracy')

In [63]:
svm_grid_model= svm_grid.fit(X_train, y_train)

Fitting 10 folds for each of 12 candidates, totalling 120 fits


[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:  1.6min finished


In [64]:
svm_grid_model

GridSearchCV(cv=10, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 100, 500, 1000)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=1)

In [65]:
svm_grid_model.best_estimator_

SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [66]:
svm_grid_model.best_params_

{'C': 100}

In [67]:
svmgrid_model= svm_grid_model.best_estimator_

In [68]:
svmgrid_predict= svmgrid_model.predict(X_test)

In [69]:
svmgrid_predict

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0], dtype=int64)

In [70]:
print('Accuracy Score: ', accuracy_score(y_test, svmgrid_predict))

Accuracy Score:  0.7549019607843137


#### Polynomial Model

In [72]:
svm_2= svm.SVC(kernel='poly', degree=2, C=0.1)

In [73]:
svm_2_model= svm_2.fit(X_train, y_train)

In [74]:
svm_2_predict= svm_2_model.predict(X_test)

In [75]:
svm_2_predict

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1], dtype=int64)

In [77]:
svm_2.n_support_

array([190, 195])

In [76]:
print('Accuracy Score: ', accuracy_score(y_test, svm_2_predict))

Accuracy Score:  0.5784313725490197


###### Polynomial with Grid Search

In [78]:
svm_3= svm.SVC(kernel='poly')

In [79]:
svm_3_grid= GridSearchCV(estimator=svm_3, param_grid=params, n_jobs=-1, cv=10, verbose=1, scoring='accuracy')

In [80]:
svm3_grid_model= svm_3_grid.fit(X_train, y_train)

Fitting 10 folds for each of 12 candidates, totalling 120 fits


[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:    9.9s finished


In [82]:
svm3_grid_model

GridSearchCV(cv=10, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'C': (0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10, 100, 500, 1000)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=1)

In [81]:
svm3_grid_model.best_params_

{'C': 1}

In [83]:
svm3_grid_model.best_estimator_

SVC(C=1, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [84]:
svm3grid_model= svm3_grid_model.best_estimator_

In [85]:
svm3grid_predict= svm3grid_model.predict(X_test)

In [86]:
svm3grid_predict

array([1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1], dtype=int64)

In [87]:
print('Accuracy Score: ', accuracy_score(y_test, svm3grid_predict))

Accuracy Score:  0.6176470588235294


#### Radial Model

In [88]:
svm_4= svm.SVC(kernel='rbf', gamma=0.5, C=10)

In [89]:
svm_4_model= svm_4.fit(X_train, y_train)

In [90]:
svm_4_predict= svm_4_model.predict(X_test)

In [91]:
svm_4_predict

array([1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1], dtype=int64)

In [92]:
svm_4.n_support_

array([190, 214])

In [93]:
print('Accuracy Score: ', accuracy_score(y_test, svm_4_predict))

Accuracy Score:  0.6372549019607843


###### Radial Model with Grid Search

In [94]:
params_2= {'C':(0.01,0.05,0.1,0.5,1,5,10,50),
          'gamma':(0.001, 0.01,0.1,0.5,1)}

In [95]:
svm_5= svm.SVC(kernel='rbf')

In [96]:
svm_5_grid= GridSearchCV(estimator=svm_5, param_grid=params_2, n_jobs=-1, cv=3, verbose=1, scoring='accuracy')

In [97]:
svm5_grid_model= svm_5_grid.fit(X_train, y_train)

Fitting 3 folds for each of 40 candidates, totalling 120 fits


[Parallel(n_jobs=-1)]: Done 120 out of 120 | elapsed:    9.8s finished


In [98]:
svm5_grid_model

GridSearchCV(cv=3, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=-1,
       param_grid={'C': (0.01, 0.05, 0.1, 0.5, 1, 5, 10, 50), 'gamma': (0.001, 0.01, 0.1, 0.5, 1)},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='accuracy', verbose=1)

In [99]:
svm5_grid_model.best_params_

{'C': 50, 'gamma': 0.001}

In [100]:
svm5_grid_model.best_estimator_

SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.001, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [101]:
svm5grid_model= svm5_grid_model.best_estimator_

In [102]:
svm5grid_predict= svm5grid_model.predict(X_test)

In [103]:
svm5grid_predict

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0], dtype=int64)

In [104]:
print('Accuracy Score: ', accuracy_score(y_test, svm5grid_predict))

Accuracy Score:  0.7549019607843137
